const typography = {
  body: {
    small: {
      fontSize: 12,
      fontStyle: 'normal',
      fontWeight: '400',
      lineHeight: 16,
    },
    medium: {
      fontSize: 14,
      fontStyle: 'normal',
      fontWeight: '400',
      lineHeight: 20,
      letterSpacing: 0.25,
    },
    large: {
      fontSize: 16,
      fontStyle: 'normal',
      fontWeight: '400',
      lineHeight: 24,
      letterSpacing: 0.5,
    },
  },
  label: {
    small: {
      fontSize: 11,
      fontStyle: 'normal',
      fontWeight: '400',
      lineHeight: 16,
      letterSpacing: 0.5,
    },
    medium: {
      fontSize: 12,
      fontStyle: 'normal',
      fontWeight: '400',
      lineHeight: 16,
      letterSpacing: 0.5,
    },
    mediumProminent: {
      fontSize: 12,
      fontStyle: 'normal',
      fontWeight: '700',
      lineHeight: 16,
      letterSpacing: 0.5,
    },
    large: {
      fontSize: 14,
      fontStyle: 'normal',
      fontWeight: '400',
      lineHeight: 20,
      letterSpacing: 0.1,
    },
    largeProminent: {
      fontSize: 14,
      fontStyle: 'normal',
      fontWeight: '700',
      lineHeight: 20,
      letterSpacing: 0.1,
    },
  },
  title: {
    small: {
      fontSize: 11,
      fontStyle: 'normal',
      fontWeight: '500',
      lineHeight: 16 /* 145.455% */,
      letterSpacing: 0.5,
    },
    medium: {
      fontSize: 12,
      fontStyle: 'normal',
      fontWeight: '500',
      lineHeight: 16 /* 133.333% */,
      letterSpacing: 0.5,
    },
    large: {
      fontSize: 22,
      fontStyle: 'normal',
      fontWeight: '400',
      lineHeight: 28 /* 127.273% */,
    },
  },
  headline: {
    small: {
      fontSize: 28,
      fontStyle: 'normal',
      fontWeight: '400',
      lineHeight: 36 /* 128.571% */,
    },
    medium: {
      fontSize: 36,
      fontStyle: 'normal',
      fontWeight: '400',
      lineHeight: 44 /* 122.222% */,
    },
    large: {
      fontSize: 32,
      fontStyle: 'normal',
      fontWeight: '400',
      lineHeight: 40 /* 125% */,
    },
  },
  display: {
    small: {
      fontSize: 36,
      fontStyle: 'normal',
      fontWeight: '400',
      lineHeight: 44 /* 122.222% */,
    },
    medium: {
      fontSize: 45,
      fontStyle: 'normal',
      fontWeight: '400',
      lineHeight: 52 /* 115.556% */,
    },
    large: {
      fontSize: 57,
      fontStyle: 'normal',
      fontWeight: '400',
      lineHeight: 64 /* 112.281% */,
      letterSpacing: -0.25,
    },
  },
} as const;

const shadows = {
  elevation1: {
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.17,
    shadowRadius: 3.05,
    elevation: 4,
  },
  elevation2: {
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.19,
    shadowRadius: 5.62,
    elevation: 6,
  },
} as const;

const state = {
  disabled: {
    defaultOpacity: 0.38,
    secondaryOpacity: 0.12,
  },
  hover: {
    stateLayerOpacity: 0.08,
  },
  focused: {
    stateLayerOpacity: 0.08,
  },
  active: {
    stateLayerOpacity: 0.1,
  },
};

export const lightTheme = {
  colors: {
    primary: '#0062a0ff',
    onPrimary: '#ffffffff',
    primaryContainer: '#d0e4ffff',
    onPrimaryContainer: '#001d35ff',
    primaryFixed: '#d0e4ffff',
    primaryFixedDim: '#9bcaffff',
    onPrimaryFixed: '#001d35ff',
    onPrimaryFixedVariant: '#004a7aff',
    error: '#ba1a1aff',
    onError: '#ffffffff',
    errorContainer: '#ffdad6ff',
    onErrorContainer: '#410002ff',
    secondary: '#506072ff',
    onSecondary: '#ffffffff',
    secondaryContainer: '#d4e4faff',
    onSecondaryContainer: '#0c1d2dff',
    secondaryFixed: '#d4e4faff',
    secondaryFixedDim: '#b8c8ddff',
    onSecondaryFixed: '#0c1d2dff',
    onSecondaryFixedVariant: '#39485aff',
    tertiary: '#6b567cff',
    onTertiary: '#ffffffff',
    tertiaryContainer: '#f1dbffff',
    onTertiaryContainer: '#251335ff',
    tertiaryFixed: '#f1dbffff',
    tertiaryFixedDim: '#d7bde9ff',
    onTertiaryFixed: '#251335ff',
    onTertiaryFixedVariant: '#523f63ff',
    surfaceDim: '#d8dae0ff',
    surface: '#f9f9fcff',
    surfaceBright: '#f9f9fcff',
    containerLowest: '#ffffffff',
    containerLow: '#f2f3f9ff',
    container: '#eceef4ff',
    containerHigh: '#e6e8eeff',
    containerHighest: '#e2e2e6ff',
    onSurface: '#1a1c1eff',
    onSurfaceVariant: '#42474eff',
    outline: '#73777fff',
    outlineVariant: '#c2c7cfff',
    inverseSurface: '#2f3033ff',
    inverseOnSurface: '#f1f0f4ff',
    inversePrimary: '#9bcaffff',
    white: '#ffffffff',
    black: '#000000ff',
    scrim: '#000000ff',
    shadow: '#000000ff',
  },
  shadows,
  state,
  typography,
} as const;

export const darkTheme = {
  colors: {
    primary: '#9bcaffff',
    onPrimary: '#003256ff',
    primaryContainer: '#004a7aff',
    onPrimaryContainer: '#d0e4ffff',
    primaryFixed: '#d0e4ffff',
    primaryFixedDim: '#9bcaffff',
    onPrimaryFixed: '#001d35ff',
    onPrimaryFixedVariant: '#004a7aff',
    error: '#ffb4abff',
    onError: '#690005ff',
    errorContainer: '#93000aff',
    onErrorContainer: '#ffdad6ff',
    secondary: '#b8c8ddff',
    onSecondary: '#223242ff',
    secondaryContainer: '#39485aff',
    onSecondaryContainer: '#d4e4faff',
    secondaryFixed: '#d4e4faff',
    secondaryFixedDim: '#b8c8ddff',
    onSecondaryFixed: '#0c1d2dff',
    onSecondaryFixedVariant: '#39485aff',
    tertiary: '#d7bde9ff',
    onTertiary: '#3b284cff',
    tertiaryContainer: '#523f63ff',
    onTertiaryContainer: '#f1dbffff',
    tertiaryFixed: '#f1dbffff',
    tertiaryFixedDim: '#d7bde9ff',
    onTertiaryFixed: '#251335ff',
    onTertiaryFixedVariant: '#523f63ff',
    surfaceDim: '#101418ff',
    surface: '#101418ff',
    surfaceBright: '#36393eff',
    containerLowest: '#191c20ff',
    containerLow: '#1a1c1eff',
    container: '#1d2024ff',
    containerHigh: '#272a2fff',
    containerHighest: '#32353aff',
    onSurface: '#e2e2e6ff',
    onSurfaceVariant: '#c2c7cfff',
    outline: '#73777fff',
    outlineVariant: '#42474eff',
    inverseSurface: '#e2e2e6ff',
    inverseOnSurface: '#2f3033ff',
    inversePrimary: '#0062a0ff',
    white: '#000000ff',
    black: '#ffffffff',
    scrim: '#000000ff',
    shadow: '#000000ff',
  },
  shadows,
  state,
  typography,
} as const;
